package dl;
// Generated 19/10/2016 17:26:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private Integer idAcceso;
     private Rutina rutina;
     private Usuario usuario;
     private int numeroAcceso;
     private int numDiasRetraso;
     private Date fechaUltimoAcceso;
     private Set rutinas = new HashSet(0);

    public Acceso() {
    }

	
    public Acceso(int numeroAcceso, int numDiasRetraso, Date fechaUltimoAcceso) {
        this.numeroAcceso = numeroAcceso;
        this.numDiasRetraso = numDiasRetraso;
        this.fechaUltimoAcceso = fechaUltimoAcceso;
    }
    public Acceso(Rutina rutina, Usuario usuario, int numeroAcceso, int numDiasRetraso, Date fechaUltimoAcceso, Set rutinas) {
       this.rutina = rutina;
       this.usuario = usuario;
       this.numeroAcceso = numeroAcceso;
       this.numDiasRetraso = numDiasRetraso;
       this.fechaUltimoAcceso = fechaUltimoAcceso;
       this.rutinas = rutinas;
    }
   
    public Integer getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(Integer idAcceso) {
        this.idAcceso = idAcceso;
    }
    public Rutina getRutina() {
        return this.rutina;
    }
    
    public void setRutina(Rutina rutina) {
        this.rutina = rutina;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getNumeroAcceso() {
        return this.numeroAcceso;
    }
    
    public void setNumeroAcceso(int numeroAcceso) {
        this.numeroAcceso = numeroAcceso;
    }
    public int getNumDiasRetraso() {
        return this.numDiasRetraso;
    }
    
    public void setNumDiasRetraso(int numDiasRetraso) {
        this.numDiasRetraso = numDiasRetraso;
    }
    public Date getFechaUltimoAcceso() {
        return this.fechaUltimoAcceso;
    }
    
    public void setFechaUltimoAcceso(Date fechaUltimoAcceso) {
        this.fechaUltimoAcceso = fechaUltimoAcceso;
    }
    public Set getRutinas() {
        return this.rutinas;
    }
    
    public void setRutinas(Set rutinas) {
        this.rutinas = rutinas;
    }




}


