package dl;
// Generated 06-sep-2016 7:16:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deportista generated by hbm2java
 */
public class Deportista  implements java.io.Serializable {


     private Integer idDeportista;
     private String primerNombre;
     private String segundoNombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String genero;
     private String cedula;
     private String correo;
     private Date fechaNacimiento;
     private int edad;
     private String facebook;
     private String celular;
     private String telefonoFijo;
     private Set MAntropometricases = new HashSet(0);

    public Deportista() {
    }

	
    public Deportista(String primerNombre, String segundoNombre, String apellidoPaterno, String apellidoMaterno, String genero, String cedula, Date fechaNacimiento, int edad, String celular, String telefonoFijo) {
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.genero = genero;
        this.cedula = cedula;
        this.fechaNacimiento = fechaNacimiento;
        this.edad = edad;
        this.celular = celular;
        this.telefonoFijo = telefonoFijo;
    }
    public Deportista(String primerNombre, String segundoNombre, String apellidoPaterno, String apellidoMaterno, String genero, String cedula, String correo, Date fechaNacimiento, int edad, String facebook, String celular, String telefonoFijo, Set MAntropometricases) {
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.genero = genero;
       this.cedula = cedula;
       this.correo = correo;
       this.fechaNacimiento = fechaNacimiento;
       this.edad = edad;
       this.facebook = facebook;
       this.celular = celular;
       this.telefonoFijo = telefonoFijo;
       this.MAntropometricases = MAntropometricases;
    }
   
    public Integer getIdDeportista() {
        return this.idDeportista;
    }
    
    public void setIdDeportista(Integer idDeportista) {
        this.idDeportista = idDeportista;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public Set getMAntropometricases() {
        return this.MAntropometricases;
    }
    
    public void setMAntropometricases(Set MAntropometricases) {
        this.MAntropometricases = MAntropometricases;
    }




}


