package dl;
// Generated 19/10/2016 17:26:37 by Hibernate Tools 4.3.1



/**
 * Ejercicio generated by hbm2java
 */
public class Ejercicio  implements java.io.Serializable {


     private Integer idEjercicio;
     private Musculo musculo;
     private String descripcionEjercicio;
     private String imagenMaquina;
     private int numeroSeries;
     private int numeroRepeticiones;
     private float peso;

    public Ejercicio() {
    }

	
    public Ejercicio(String descripcionEjercicio, String imagenMaquina, int numeroSeries, int numeroRepeticiones, float peso) {
        this.descripcionEjercicio = descripcionEjercicio;
        this.imagenMaquina = imagenMaquina;
        this.numeroSeries = numeroSeries;
        this.numeroRepeticiones = numeroRepeticiones;
        this.peso = peso;
    }
    public Ejercicio(Musculo musculo, String descripcionEjercicio, String imagenMaquina, int numeroSeries, int numeroRepeticiones, float peso) {
       this.musculo = musculo;
       this.descripcionEjercicio = descripcionEjercicio;
       this.imagenMaquina = imagenMaquina;
       this.numeroSeries = numeroSeries;
       this.numeroRepeticiones = numeroRepeticiones;
       this.peso = peso;
    }
   
    public Integer getIdEjercicio() {
        return this.idEjercicio;
    }
    
    public void setIdEjercicio(Integer idEjercicio) {
        this.idEjercicio = idEjercicio;
    }
    public Musculo getMusculo() {
        return this.musculo;
    }
    
    public void setMusculo(Musculo musculo) {
        this.musculo = musculo;
    }
    public String getDescripcionEjercicio() {
        return this.descripcionEjercicio;
    }
    
    public void setDescripcionEjercicio(String descripcionEjercicio) {
        this.descripcionEjercicio = descripcionEjercicio;
    }
    public String getImagenMaquina() {
        return this.imagenMaquina;
    }
    
    public void setImagenMaquina(String imagenMaquina) {
        this.imagenMaquina = imagenMaquina;
    }
    public int getNumeroSeries() {
        return this.numeroSeries;
    }
    
    public void setNumeroSeries(int numeroSeries) {
        this.numeroSeries = numeroSeries;
    }
    public int getNumeroRepeticiones() {
        return this.numeroRepeticiones;
    }
    
    public void setNumeroRepeticiones(int numeroRepeticiones) {
        this.numeroRepeticiones = numeroRepeticiones;
    }
    public float getPeso() {
        return this.peso;
    }
    
    public void setPeso(float peso) {
        this.peso = peso;
    }




}


