package dl;
// Generated 19/10/2016 17:26:37 by Hibernate Tools 4.3.1



/**
 * Impedimentos generated by hbm2java
 */
public class Impedimentos  implements java.io.Serializable {


     private Integer idImpedimento;
     private Deportista deportista;
     private String descripcion;

    public Impedimentos() {
    }

	
    public Impedimentos(String descripcion) {
        this.descripcion = descripcion;
    }
    public Impedimentos(Deportista deportista, String descripcion) {
       this.deportista = deportista;
       this.descripcion = descripcion;
    }
   
    public Integer getIdImpedimento() {
        return this.idImpedimento;
    }
    
    public void setIdImpedimento(Integer idImpedimento) {
        this.idImpedimento = idImpedimento;
    }
    public Deportista getDeportista() {
        return this.deportista;
    }
    
    public void setDeportista(Deportista deportista) {
        this.deportista = deportista;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


