package dl;
// Generated 06-sep-2016 7:16:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MAntropometricas generated by hbm2java
 */
public class MAntropometricas  implements java.io.Serializable {


     private Integer idMAntropomrtricas;
     private Deportista deportista;
     private BigDecimal peso;
     private BigDecimal talla;
     private BigDecimal brazoIzquierdo;
     private BigDecimal brazoDerecho;
     private BigDecimal pecho;
     private BigDecimal cintura;
     private BigDecimal cadera;
     private BigDecimal muslo;
     private BigDecimal pantorrillas;
     private BigDecimal irm;
     private BigDecimal grasaCorporal;

    public MAntropometricas() {
    }

	
    public MAntropometricas(BigDecimal peso, BigDecimal talla, BigDecimal brazoIzquierdo, BigDecimal brazoDerecho, BigDecimal pecho, BigDecimal cintura, BigDecimal muslo, BigDecimal pantorrillas) {
        this.peso = peso;
        this.talla = talla;
        this.brazoIzquierdo = brazoIzquierdo;
        this.brazoDerecho = brazoDerecho;
        this.pecho = pecho;
        this.cintura = cintura;
        this.muslo = muslo;
        this.pantorrillas = pantorrillas;
    }
    public MAntropometricas(Deportista deportista, BigDecimal peso, BigDecimal talla, BigDecimal brazoIzquierdo, BigDecimal brazoDerecho, BigDecimal pecho, BigDecimal cintura, BigDecimal cadera, BigDecimal muslo, BigDecimal pantorrillas, BigDecimal irm, BigDecimal grasaCorporal) {
       this.deportista = deportista;
       this.peso = peso;
       this.talla = talla;
       this.brazoIzquierdo = brazoIzquierdo;
       this.brazoDerecho = brazoDerecho;
       this.pecho = pecho;
       this.cintura = cintura;
       this.cadera = cadera;
       this.muslo = muslo;
       this.pantorrillas = pantorrillas;
       this.irm = irm;
       this.grasaCorporal = grasaCorporal;
    }
   
    public Integer getIdMAntropomrtricas() {
        return this.idMAntropomrtricas;
    }
    
    public void setIdMAntropomrtricas(Integer idMAntropomrtricas) {
        this.idMAntropomrtricas = idMAntropomrtricas;
    }
    public Deportista getDeportista() {
        return this.deportista;
    }
    
    public void setDeportista(Deportista deportista) {
        this.deportista = deportista;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }
    public BigDecimal getBrazoIzquierdo() {
        return this.brazoIzquierdo;
    }
    
    public void setBrazoIzquierdo(BigDecimal brazoIzquierdo) {
        this.brazoIzquierdo = brazoIzquierdo;
    }
    public BigDecimal getBrazoDerecho() {
        return this.brazoDerecho;
    }
    
    public void setBrazoDerecho(BigDecimal brazoDerecho) {
        this.brazoDerecho = brazoDerecho;
    }
    public BigDecimal getPecho() {
        return this.pecho;
    }
    
    public void setPecho(BigDecimal pecho) {
        this.pecho = pecho;
    }
    public BigDecimal getCintura() {
        return this.cintura;
    }
    
    public void setCintura(BigDecimal cintura) {
        this.cintura = cintura;
    }
    public BigDecimal getCadera() {
        return this.cadera;
    }
    
    public void setCadera(BigDecimal cadera) {
        this.cadera = cadera;
    }
    public BigDecimal getMuslo() {
        return this.muslo;
    }
    
    public void setMuslo(BigDecimal muslo) {
        this.muslo = muslo;
    }
    public BigDecimal getPantorrillas() {
        return this.pantorrillas;
    }
    
    public void setPantorrillas(BigDecimal pantorrillas) {
        this.pantorrillas = pantorrillas;
    }
    public BigDecimal getIrm() {
        return this.irm;
    }
    
    public void setIrm(BigDecimal irm) {
        this.irm = irm;
    }
    public BigDecimal getGrasaCorporal() {
        return this.grasaCorporal;
    }
    
    public void setGrasaCorporal(BigDecimal grasaCorporal) {
        this.grasaCorporal = grasaCorporal;
    }




}


