package dl;
// Generated 24/10/2016 17:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Metas generated by hbm2java
 */
public class Metas  implements java.io.Serializable {


     private Integer idMeta;
     private Deportista deportista;
     private String descripcion;
     private Set planificacions = new HashSet(0);

    public Metas() {
    }

	
    public Metas(String descripcion) {
        this.descripcion = descripcion;
    }
    public Metas(Deportista deportista, String descripcion, Set planificacions) {
       this.deportista = deportista;
       this.descripcion = descripcion;
       this.planificacions = planificacions;
    }
   
    public Integer getIdMeta() {
        return this.idMeta;
    }
    
    public void setIdMeta(Integer idMeta) {
        this.idMeta = idMeta;
    }
    public Deportista getDeportista() {
        return this.deportista;
    }
    
    public void setDeportista(Deportista deportista) {
        this.deportista = deportista;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPlanificacions() {
        return this.planificacions;
    }
    
    public void setPlanificacions(Set planificacions) {
        this.planificacions = planificacions;
    }




}


