package dl;
// Generated 24/10/2016 17:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private String descPerfil;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }
    public Perfil(String descPerfil, Set usuarios) {
       this.descPerfil = descPerfil;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getDescPerfil() {
        return this.descPerfil;
    }
    
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


