package dl;
// Generated 24/10/2016 17:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Planificacion generated by hbm2java
 */
public class Planificacion  implements java.io.Serializable {


     private Integer idPlanificacion;
     private MAntropometricas MAntropometricas;
     private Metas metas;
     private int intensidad;
     private String objetivo;
     private int numMaxDias;
     private Set rutinas = new HashSet(0);

    public Planificacion() {
    }

	
    public Planificacion(int intensidad, String objetivo, int numMaxDias) {
        this.intensidad = intensidad;
        this.objetivo = objetivo;
        this.numMaxDias = numMaxDias;
    }
    public Planificacion(MAntropometricas MAntropometricas, Metas metas, int intensidad, String objetivo, int numMaxDias, Set rutinas) {
       this.MAntropometricas = MAntropometricas;
       this.metas = metas;
       this.intensidad = intensidad;
       this.objetivo = objetivo;
       this.numMaxDias = numMaxDias;
       this.rutinas = rutinas;
    }
   
    public Integer getIdPlanificacion() {
        return this.idPlanificacion;
    }
    
    public void setIdPlanificacion(Integer idPlanificacion) {
        this.idPlanificacion = idPlanificacion;
    }
    public MAntropometricas getMAntropometricas() {
        return this.MAntropometricas;
    }
    
    public void setMAntropometricas(MAntropometricas MAntropometricas) {
        this.MAntropometricas = MAntropometricas;
    }
    public Metas getMetas() {
        return this.metas;
    }
    
    public void setMetas(Metas metas) {
        this.metas = metas;
    }
    public int getIntensidad() {
        return this.intensidad;
    }
    
    public void setIntensidad(int intensidad) {
        this.intensidad = intensidad;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public int getNumMaxDias() {
        return this.numMaxDias;
    }
    
    public void setNumMaxDias(int numMaxDias) {
        this.numMaxDias = numMaxDias;
    }
    public Set getRutinas() {
        return this.rutinas;
    }
    
    public void setRutinas(Set rutinas) {
        this.rutinas = rutinas;
    }




}


